### ISSUE TITLE
Error while running parse_programs script with gen_prog

### ISSUE THREAD

**Issue by shankyemcee** [wenhuchen/LogicNLG#12]
The command i ran:

python parse_programs.py --gen_prog

and the error:

Traceback (most recent call last):
  File "parse_programs.py", line 215, in <module>
    with open('data/bootstrap.json') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/bootstrap.json'

I also dont see this bootstrap.json file anywhere in the data folder.

**Comment by wenhuchen** [comment]
Sorry for the late reply, somehow I missed your message. I added the bootstrap.json to the repo. This is from the original TabFact GitHub repo, a small-scale annotated program-text pairs.
