### ISSUE TITLE
Question about predictions

### ISSUE THREAD

**Issue by ixn872** [wenhuchen/LogicNLG#16]
Thank you for this repository. I would like to ask you, what is the correct way to use the GPT-2 model version to generate summaries over new table.

**Comment by wenhuchen** [comment]
Could you encode your table as a JSON file (the same format as the ones in the repo)? Then maybe you revise the https://github.com/wenhuchen/LogicNLG/blob/4b8b4f10bbadf93ad22a69fd31862b2061761a3d/GPT2.py#L211 to specifically read your table file as the input.
