### ISSUE TITLE
What is the difference between full_vocab.json and vocab.json, and how to construction them from a new dataset?

### ISSUE THREAD

**Issue by patronum08** [wenhuchen/LogicNLG#3]

**Comment by wenhuchen** [comment]
vocab is for the words which we need to learn embedding, full_vocab is just for bookkeeping the whole vocabulary for copy mechanism. This is a very standard way of implementing copy-pointer generation. If you have a new dataset, you can list all the unique words in the dataset and might end up having 1M words which goes to your full_vocab.json, and then you do frequency cut to get the most frequent 30K words in your vocab.json.
