### ISSUE TITLE
Besides the linearization text, what else information is needed when test? Does the column index need?

### ISSUE THREAD

**Issue by patronum08** [wenhuchen/LogicNLG#5]

**Comment by wenhuchen** [comment]
Sorry that I somehow missed your issue. For the val/test/blind test, the column index is given. If you are using training, the column index is not necessary, you can use your technique to narrow down the description to certain table columns. Our released version for column indexing is only for reference.

**Comment by patronum08** [comment]
I see. That's helpful. Thanks
