### ISSUE TITLE
This error keeps popping up when i try to run your NLI_evaluation

### ISSUE THREAD

**Issue by shankyemcee** [wenhuchen/LogicNLG#6]
Traceback (most recent call last):
  File "NLI.py", line 2, in <module>
    from NLI_models import *
  File "/content/drive/My Drive/logicnlg/NLI_models.py", line 6, in <module>
    from allennlp.nn import util
ModuleNotFoundError: No module named 'allennlp'

I am running on google colab using the command,

 CUDA_VISIBLE_DEVICES=0 python NLI.py --model bert-base-multilingual-uncased --do_verify --encoding gnn --load_from NLI_models/model_ep4.pt --fp16 --verify_file outputs/GPT_gpt2_C2F_13.35.json --verify_linking data/test_lm.json

Do i need to install allennlp seperately? and which version?

**Comment by wenhuchen** [comment]
Sorry that I somehow missed this issue, which causes the late reply. The version that I used is "allennlp 0.9.0", I use the allennlp library to do some masking function. Sorry again for the late reply.
