### ISSUE TITLE
Evaluate your model on my own table data

### ISSUE THREAD

**Issue by vnik18** [wenhuchen/LogicNLG#7]
Hello,

Thank you for sharing your great work and code. I would like to evaluate your trained models on my own test set of tables. According to the format of your file `test_lm.json`, I need 
```
[
      sent1,
      linked columns1,
      table title,
      template1
    ] 
```
I have `table title` available. `Linked columns1` and `template1` are generated by entity linking. Can you please tell me how to generate `sent1`? Is there any script for this in your code repository? Thank you.

**Comment by wenhuchen** [comment]
If I understand your question clearly, you are asking about how the text is generated, right? In my dataset, it's written by humans through the Amazon Mechnical Turker Platform.

**Comment by vnik18** [comment]
Yes, I am asking how the text in the `sent1` field of your file `test_lm.json` is generated. Thank you.
