### ISSUE TITLE
How can I create the linked columns field and template field for each reference in another dataset?

### ISSUE THREAD

**Issue by shankyemcee** [wenhuchen/LogicNLG#8]
I am using trying to evaulate logicnlg on another dataset. I have already created the data files in the format needed for logicnlg. I have created the train_lm.json, but only with the text and title field for each reference. How can i create the linking column and sentence template field for each reference ?

**Comment by wenhuchen** [comment]
The same question is asked in another issue, so please refer to my answer there. Thanks
